experimento: 4946.0
semilla_primigenia: 907871.0
train:
- 202102.0
- 202103.0
test_holdout: 202104.0
train_final:
- 202101.0
- 202102.0
- 202103.0
- 202104.0
future: 202106.0
simulacion: 202104.0
semilla_kaggle: 314159.0
cortes:
- 2000.0
- 2500.0
- 3000.0
- 3500.0
- 4000.0
- 4500.0
- 5000.0
- 5500.0
- 6000.0
- 6500.0
- 7000.0
- 7500.0
- 8000.0
- 8500.0
- 9000.0
- 9500.0
- 10000.0
- 10500.0
- 11000.0
- 11500.0
- 12000.0
- 12500.0
- 13000.0
- 13500.0
- 14000.0
- 14500.0
- 15000.0
- 15500.0
- 16000.0
- 16500.0
- 17000.0
- 17500.0
- 18000.0
- 18500.0
- 19000.0
trainingstrategy:
  undersampling: 0.3
hyperparametertuning:
  xval_folds: 5.0
  bounds:
    num_iterations:
    - 500
    - 3000
    learning_rate:
    - 0.005
    - 0.1
    feature_fraction:
    - 0.1
    - 1.0
    bagging_fraction:
    - 0.5
    - 1.0
    num_leaves:
    - 10
    - 200
    min_data_in_leaf:
    - 500
    - 4000
  iteraciones: 70.0
lgbm:
  param_fijos:
    boosting: gbdt
    objective: binary
    metric: auc
    first_metric_only: no
    boost_from_average: yes
    feature_pre_filter: no
    force_row_wise: yes
    verbosity: -100.0
    seed: 907871.0
    max_depth: -1
    min_gain_to_split: 0.0
    min_sum_hessian_in_leaf: 0.001
    lambda_l1: 0.0
    lambda_l2: 0.0
    max_bin: 31
    pos_bagging_fraction: 1.0
    neg_bagging_fraction: 1.0
    is_unbalance: no
    scale_pos_weight: 1.0
    drop_rate: 0.1
    max_drop: 50.0
    skip_drop: 0.5
    extra_trees: no
out:
  lgbm:
    mejores_hiperparametros:
      num_iterations: 2840
      learning_rate: 0.005
      feature_fraction: 0.1
      bagging_fraction: 1.0
      num_leaves: 189
      min_data_in_leaf: 500
    'y': 0.9366288
